# Generated by Django 3.1.7 on 2021-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nick_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nick_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
